import type { Spot } from './types';

export const SEED_SPOTS: Spot[] = [
  {
    id: 'spot-1',
    name: '津田沼駅前図書館 閲覧席',
    category: '図書館',
    area: '津田沼駅前',
    indoor: true,
    price: '無料',
    stayDuration: '60分以上',
    description:
      '静かな閲覧席。ノイズが少なく、時間を気にせず滞在できる数少ない場所。目的のない読書や、PCを使わない作業にも向く。混雑時は席が埋まるので注意。',
    baseScores: {
      consumptionPressure: 1,
      workTolerance: 5,
      purposePressure: 3,
      visibilityPressure: 2,
      stayTolerance: 5,
      weatherResistance: 5,
      fragility: 2,
    },
    mapX: 30,
    mapY: 25,
  },
  {
    id: 'spot-2',
    name: '駅前商業施設のベンチ',
    category: '商業施設',
    area: '津田沼駅前',
    indoor: true,
    price: '無料',
    stayDuration: '15〜30分',
    description:
      '無料で座れるが、人通りが多く目的なく長居するには少し居づらい。短時間の休憩・待ち合わせには便利。広告や音楽が常に流れている。',
    baseScores: {
      consumptionPressure: 2,
      workTolerance: 1,
      purposePressure: 3,
      visibilityPressure: 5,
      stayTolerance: 2,
      weatherResistance: 5,
      fragility: 3,
    },
    mapX: 52,
    mapY: 45,
  },
  {
    id: 'spot-3',
    name: '大学近くのイートイン',
    category: 'イートイン',
    area: '津田沼周辺',
    indoor: true,
    price: '低価格',
    stayDuration: '30分',
    description:
      '少額の購入で席を使える。学生が多く、作業している人もいるがガヤガヤしている。深く集中したい時には向かないが、ちょっとした時間つぶしには良い。',
    baseScores: {
      consumptionPressure: 3,
      workTolerance: 2,
      purposePressure: 3,
      visibilityPressure: 3,
      stayTolerance: 3,
      weatherResistance: 5,
      fragility: 3,
    },
    mapX: 70,
    mapY: 60,
  },
  {
    id: 'spot-4',
    name: '津田沼駅近くの公園ベンチ',
    category: '公園',
    area: '津田沼駅周辺',
    indoor: false,
    price: '無料',
    stayDuration: '30〜60分',
    description:
      '空が見えて、圧迫感がない。晴れた日は最高の滞在空間になり得る。ただし雨・真夏・真冬は厳しく、PCを広げるには不向き。何もしない時間のために使いたい場所。',
    baseScores: {
      consumptionPressure: 1,
      workTolerance: 1,
      purposePressure: 1,
      visibilityPressure: 2,
      stayTolerance: 3,
      weatherResistance: 1,
      fragility: 4,
    },
    mapX: 20,
    mapY: 70,
  },
  {
    id: 'spot-5',
    name: '公共施設ロビー',
    category: '公共施設',
    area: '津田沼周辺',
    indoor: true,
    price: '無料',
    stayDuration: '30〜60分',
    description:
      '市民向けの公共施設のロビー。無料で座れ、適度に静か。用事がある人が中心だが、待ち合わせや読書程度なら違和感なく滞在できる。冷暖房があり、雨の日の逃げ場にもなる。',
    baseScores: {
      consumptionPressure: 1,
      workTolerance: 3,
      purposePressure: 2,
      visibilityPressure: 3,
      stayTolerance: 4,
      weatherResistance: 5,
      fragility: 2,
    },
    mapX: 45,
    mapY: 30,
  },
  {
    id: 'spot-6',
    name: '駅近の安価なカフェ',
    category: 'カフェ',
    area: '津田沼駅前',
    indoor: true,
    price: '有料',
    stayDuration: '30〜60分',
    description:
      'コーヒー一杯で1時間程度は居やすい。Wi-Fiと電源があれば作業向き。ただし消費圧があり、長居には追加注文の空気がある。チェーン系は均質で安心感がある。',
    baseScores: {
      consumptionPressure: 4,
      workTolerance: 3,
      purposePressure: 3,
      visibilityPressure: 3,
      stayTolerance: 3,
      weatherResistance: 5,
      fragility: 2,
    },
    mapX: 60,
    mapY: 40,
  },
];
